name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: "Obtendo o código"
      uses: actions/checkout@v5.0.0
    - name: "Autenticação Docker hub"
      uses: docker/login-action@v3.5.0  
      with: 
        username: ${{secrets.DOCKERHUB_USER}}
        password: ${{secrets.DOCKERHUB_PWD}}
    - name: "Build e push image"
      uses: docker/build-push-action@v5.3.0
      with:
        context: ./src
        file: ./src/Dockerfile
        push: true
        tags: |
          joseviniciussilva/pipeline:v${{github.run_number}}
          joseviniciussilva/pipeline:latest
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
    - name: "Obtendo o código"
      uses: actions/checkout@v5.0.0
    - name: Configuração do contexto do kubernetes
      uses: Azure/k8s-set-context@v3.0
      with:
        method: kubeconfig
        kubeconfig: ${{secrets.K8S_CONFIG}}
